version: '3.1'
services:
  db:
    image: postgres
    container_name: diplom_postgres
    restart: always
    environment:
      POSTGRES_DB: diplom_db
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
    ports:
      - "5434:5432"