server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  datasource:
    url: jdbc:postgresql://localhost:5434/diplom_db
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 30
      password: admin123
      username: admin
  freemarker:
    suffix: .ftl
    template-loader-path: classpath:/templates/
